spring.application.name=faculty
spring.data.mongodb.uri=mongodb+srv://admin:o5cpdVTN44Zoi8Fq@cluster0.yawwn.mongodb.net/
spring.data.mongodb.database=facultydb
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration